package com.quickfolds.backend.origami.model.dto.response;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO (Data Transfer Object) representing the response after creating a new origami model.
 *
 * - Encapsulates the newly generated origami ID.
 * - Used to return a structured response to the client after a successful origami creation.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class NewOrigamiResponse {
    /**
     * The unique identifier of the newly created origami model.
     *
     * - Generated by the database upon successful creation.
     * - Returned to the client for future reference.
     */
    private Long origamiId;
}
