package com.quickfolds.backend.origami.model.dto.response;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO (Data Transfer Object) representing the response after creating a new origami model.
 * <p>
 * This class encapsulates the unique ID of the newly created origami model.
 * It is used to return a structured response to the client following a successful origami creation.
 * <p>
 * Key Field:
 * <ul>
 *     <li><strong>origamiId:</strong> The unique identifier generated by the database for the created origami.</li>
 * </ul>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class NewOrigamiResponse {

    /**
     * The unique identifier of the newly created origami model.
     * <p>
     * This ID is generated by the database upon successful insertion of the origami record.
     * It allows the client to reference the origami for future operations, such as editing or sharing.
     */
    private Long origamiId;
}