services:
  postgres_local:
    image: postgres:15
    container_name: quickfolds-db-local
    restart: always
    env_file:
      - env/local.env  # Loads only local variables
    environment:
      POSTGRES_USER: "${LOCAL_DB_USER}"
      POSTGRES_PASSWORD: "${LOCAL_DB_PASSWORD}"
      POSTGRES_DB: "${LOCAL_DB_NAME}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_local_data:/var/lib/postgresql/data

  postgres_dev:
    image: postgres:15
    container_name: quickfolds-db-dev
    restart: always
    env_file:
      - env/dev.env  # Loads only dev variables
    environment:
      POSTGRES_USER: "${DEV_DB_USER}"
      POSTGRES_PASSWORD: "${DEV_DB_PASSWORD}"
      POSTGRES_DB: "${DEV_DB_NAME}"
    ports:
      - "5434:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:15
    container_name: quickfolds-db-test
    restart: always
    env_file:
      - env/test.env  # Loads only test variables
    environment:
      POSTGRES_USER: "${TEST_DB_USER}"
      POSTGRES_PASSWORD: "${TEST_DB_PASSWORD}"
      POSTGRES_DB: "${TEST_DB_NAME}"
    ports:
      - "5435:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_local_data:
  postgres_dev_data:
  postgres_test_data:
