spring:
  datasource:
    url: jdbc:postgresql://${TEST_DB_HOST}:${TEST_DB_PORT}/${TEST_DB_NAME}
    username: ${TEST_DB_USER}
    password: ${TEST_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

mybatis:
  mapper-locations: classpath:mappers/**/*.xml

jwt:
  secret: ${JWT_SECRET:secret}
