spring:
  datasource:
    url: jdbc:postgresql://${LOCAL_DB_HOST}:${LOCAL_DB_PORT}/${LOCAL_DB_NAME}
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET:secret}

logging:
  level:
    root: DEBUG # Root log
    com.quickfolds.backend: DEBUG # Backend log
    org.apache.coyote.http11.Http11InputBuffer: DEBUG # Incoming HTTP requests
    org.springframework.security: DEBUG # Security log
    org.springframework.jdbc.datasource.init: DEBUG # SQL init log
    org.springframework.jdbc.core: DEBUG # SQL log
