package com.quickfolds.backend.geometry.model.database;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.OffsetDateTime;

/**
 * Represents an annotated line associated with a specific face of an origami model during a defined step.
 * <p>
 * This entity stores metadata about the line, including the points it connects,
 * its position within the face, and lifecycle information such as creation and deletion steps.
 * <p>
 * Maps to the "annotated_line" table in the database.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "annotated_line")
public class AnnotatedLine {

    /**
     * Unique identifier for the annotated line.
     * <p>
     * - Auto-generated by the database using identity strategy.
     * - Cannot be null and cannot be updated after creation.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, updatable = false)
    private Long id;

    /**
     * Foreign key referencing the step where this line was annotated.
     * <p>
     * - Cannot be null.
     * - Links to a specific step in the "step" table.
     */
    @Column(name = "step_id", nullable = false)
    private Long stepId;

    /**
     * Foreign key referencing the face to which this annotated line belongs.
     * <p>
     * - Cannot be null.
     * - Links to a specific face in the "face" table.
     */
    @Column(name = "face_id", nullable = false)
    private Long faceId;

    /**
     * Foreign key referencing the first point of the line.
     * <p>
     * - Cannot be null.
     * - Links to a specific point in the "origami_point" table.
     */
    @Column(name = "point_1_id", nullable = false)
    private Long point1Id;

    /**
     * Foreign key referencing the second point of the line.
     * <p>
     * - Cannot be null.
     * - Links to a specific point in the "origami_point" table.
     */
    @Column(name = "point_2_id", nullable = false)
    private Long point2Id;

    /**
     * The line number within the face.
     * <p>
     * - Used to differentiate multiple annotated lines within the same face.
     * - Cannot be null.
     */
    @Column(name = "id_in_face", nullable = false)
    private Integer idInFace;

    /**
     * Foreign key referencing the step where this annotated line was deleted.
     * <p>
     * - Null if the line has not been deleted.
     * - Links to a specific step in the "step" table.
     */
    @Column(name = "deleted_step_id")
    private Long deletedStepId;

    /**
     * Identifier of the user who created this annotated line record.
     * <p>
     * - May be null if not explicitly set during creation.
     */
    @Column(name = "created_by")
    private String createdBy;

    /**
     * Identifier of the user who last updated this annotated line record.
     * <p>
     * - May be null if the record has not been updated.
     */
    @Column(name = "updated_by")
    private String updatedBy;

    /**
     * Timestamp indicating when this annotated line record was created.
     * <p>
     * - Automatically set at creation.
     * - Cannot be updated once created.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /**
     * Timestamp indicating when this annotated line record was last updated.
     * <p>
     * - Automatically updated whenever the record is modified.
     * - May be null if no updates have occurred since creation.
     */
    @Column(name = "updated_at")
    private OffsetDateTime updatedAt;
}