package com.quickfolds.backend.geometry.model.database;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.OffsetDateTime;

/**
 * Represents an edge in an origami model, including side edges and fold edges.
 * <p>
 * This entity maps to the "edge" table in the database and includes metadata
 * such as creation step, type, and lifecycle timestamps.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "edge")
public class Edge {

    /**
     * Unique identifier for the edge.
     * <p>
     * - Auto-generated by the database using identity strategy.
     * - Cannot be null and cannot be updated after creation.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, updatable = false)
    private Long id;

    /**
     * Foreign key referencing the step in which this edge was created.
     * <p>
     * - Cannot be null.
     * - Links to a specific step in the "step" table.
     */
    @Column(name = "step_id", nullable = false)
    private Long stepId;

    /**
     * Foreign key referencing the type of edge (e.g., side or fold).
     * <p>
     * - Cannot be null.
     * - Links to a specific edge type in the "edge_type" table.
     */
    @Column(name = "edge_type_id", nullable = false)
    private Long edgeTypeId;

    /**
     * Foreign key referencing the step where this edge was marked as deleted.
     * <p>
     * - Null if the edge is still active.
     * - Links to a specific step in the "step" table.
     */
    @Column(name = "deleted_step_id")
    private Long deletedStepId;

    /**
     * Identifier of the user who created this edge record.
     * <p>
     * - May be null if not explicitly set.
     */
    @Column(name = "created_by")
    private String createdBy;

    /**
     * Identifier of the user who last updated this edge record.
     * <p>
     * - May be null if not explicitly set.
     */
    @Column(name = "updated_by")
    private String updatedBy;

    /**
     * Timestamp indicating when this edge record was created.
     * <p>
     * - Automatically set at creation.
     * - Cannot be updated once created.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /**
     * Timestamp indicating when this edge record was last updated.
     * <p>
     * - Updated automatically when the record is modified.
     * - Can be null if no updates have occurred.
     */
    @Column(name = "updated_at")
    private OffsetDateTime updatedAt;
}