package com.quickfolds.backend.geometry.model.database;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Id;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.OffsetDateTime;

/**
 * Represents a face of an origami model, typically created during a specific step in the process.
 * <p>
 * This entity maps to the "face" table in the database and stores metadata about the face,
 * including its creation step, deletion step, and user activity.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "face")
public class Face {

    /**
     * Primary key for the Face table.
     * <p>
     * - Auto-generated by the database using identity strategy.
     * - Cannot be null and cannot be updated after creation.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, updatable = false)
    private Long id;

    /**
     * Foreign key referencing the step during which this face was created.
     * <p>
     * - Cannot be null.
     * - Links to a specific step in the "step" table.
     */
    @Column(name = "step_id", nullable = false)
    private Long stepId;

    /**
     * A unique identifier for this face within an origami model.
     * <p>
     * - Used to differentiate multiple faces belonging to the same origami.
     * - Cannot be null.
     */
    @Column(name = "id_in_origami", nullable = false)
    private Integer idInOrigami;

    /**
     * The ID of the step in which this face was deleted, if applicable.
     * <p>
     * - Null if the face has not been deleted.
     * - Links to a specific step in the "step" table.
     */
    @Column(name = "deleted_step_id")
    private Long deletedStepId;

    /**
     * Identifier of the user who created this face record.
     * <p>
     * - May be null if not explicitly set.
     */
    @Column(name = "created_by")
    private String createdBy;

    /**
     * Identifier of the user who last updated this face record.
     * <p>
     * - May be null if not explicitly set.
     */
    @Column(name = "updated_by")
    private String updatedBy;

    /**
     * Timestamp indicating when this face record was created.
     * <p>
     * - Automatically set at the time of creation.
     * - Cannot be updated once created.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /**
     * Timestamp indicating when this face record was last updated.
     * <p>
     * - Updated automatically when the record is modified.
     * - May be null if no updates have occurred.
     */
    @Column(name = "updated_at")
    private OffsetDateTime updatedAt;
}