package com.quickfolds.backend.geometry.model.database;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.OffsetDateTime;

/**
 * Represents a point in the origami model, belonging to a specific face and step.
 * <p>
 * This entity maps to the "origami_point" table in the database and stores the
 * coordinates, type, and metadata associated with each point.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "origami_point")
public class OrigamiPoint {

    /**
     * Unique identifier for the origami point.
     * <p>
     * - Auto-generated by the database using identity strategy.
     * - Cannot be null and cannot be updated after creation.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, updatable = false)
    private Long id;

    /**
     * Foreign key referencing the step in which this point was created.
     * <p>
     * - Cannot be null.
     * - Links to a specific step in the "step" table.
     */
    @Column(name = "step_id", nullable = false)
    private Long stepId;

    /**
     * Foreign key referencing the face to which this point belongs.
     * <p>
     * - Cannot be null.
     * - Links to a specific face in the "face" table.
     */
    @Column(name = "face_id", nullable = false)
    private Long faceId;

    /**
     * Foreign key referencing the type of this point (e.g., vertex, annotated_point).
     * <p>
     * - Cannot be null.
     * - Links to a specific point type in the "point_type" table.
     */
    @Column(name = "point_type_id", nullable = false)
    private Long pointTypeId;

    /**
     * X-coordinate of the point in the origami model.
     * <p>
     * - Cannot be null.
     * - Represents the horizontal position within the face.
     */
    @Column(name = "x_pos", nullable = false)
    private Double xPos;

    /**
     * Y-coordinate of the point in the origami model.
     * <p>
     * - Cannot be null.
     * - Represents the vertical position within the face.
     */
    @Column(name = "y_pos", nullable = false)
    private Double yPos;

    /**
     * Identifies this point within the face.
     * <p>
     * - Cannot be null.
     * - Used to differentiate multiple points within the same face.
     */
    @Column(name = "id_in_face", nullable = false)
    private Integer idInFace;

    /**
     * Foreign key referencing the step where this point was marked as deleted.
     * <p>
     * - Null if the point is still active.
     * - Links to a specific step in the "step" table.
     */
    @Column(name = "deleted_step_id")
    private Long deletedStepId;

    /**
     * Identifier of the user who created this point record.
     * <p>
     * - May be null if not explicitly set.
     */
    @Column(name = "created_by")
    private String createdBy;

    /**
     * Identifier of the user who last updated this point record.
     * <p>
     * - May be null if not explicitly set.
     */
    @Column(name = "updated_by")
    private String updatedBy;

    /**
     * Timestamp when this point record was created.
     * <p>
     * - Automatically set at the time of creation.
     * - Cannot be updated once created.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /**
     * Timestamp when this point record was last updated.
     * <p>
     * - Updated automatically when the record is modified.
     * - Can be null if no updates have occurred.
     */
    @Column(name = "updated_at")
    private OffsetDateTime updatedAt;
}