package com.quickfolds.backend.geometry.model.database;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.OffsetDateTime;

/**
 * Represents the type of step in the origami process (e.g., fold, annotate).
 * <p>
 * This entity maps to the "step_type" table in the database and defines categories
 * of steps used to track the origami folding process.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "step_type")
public class StepType {

    /**
     * Primary key for the StepType table.
     * <p>
     * - Auto-generated by the database using identity strategy.
     * - Cannot be null and cannot be updated after creation.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, updatable = false)
    private Long id;

    /**
     * The name of the step type, such as "fold" or "annotate".
     * <p>
     * - Must be unique across all step types.
     * - Cannot be null.
     */
    @Column(name = "step_type_name", nullable = false, unique = true)
    private String stepTypeName;

    /**
     * Identifier of the user who created this step type record.
     * <p>
     * - May be null if not explicitly set.
     */
    @Column(name = "created_by")
    private String createdBy;

    /**
     * Identifier of the user who last updated this step type record.
     * <p>
     * - May be null if not explicitly set.
     */
    @Column(name = "updated_by")
    private String updatedBy;

    /**
     * Timestamp when this step type record was created.
     * <p>
     * - Automatically set at the time of creation.
     * - Cannot be updated after creation.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /**
     * Timestamp when this step type record was last updated.
     * <p>
     * - Updated automatically when the record is modified.
     * - Can be null if no updates have occurred.
     */
    @Column(name = "updated_at")
    private OffsetDateTime updatedAt;
}